version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "gomod"
    directory: "/core"
    schedule:
      interval: "monthly"

  - package-ecosystem: "gomod"
    directory: "/bindings/go"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/bindings/js"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pip"
    directory: "/bindings/python"
    schedule:
      interval: "monthly"

  - package-ecosystem: "bundler"
    directory: "/bindings/ruby"
    schedule:
      interval: "monthly"

  - package-ecosystem: "maven"
    directory: "/bindings/java"
    schedule:
      interval: "monthly"
